name: GitHub Actions Test
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow_dispatch]
jobs:
  Testing-Terraform-Plan:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run build repository
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          ls ${{ github.workspace }}
          bash --version
          (
            cd source
            ls -laR
            terraform init
            terraform plan
          )
  Testing-Terraform-Apply:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run build repository
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          ls ${{ github.workspace }}
          bash --version
          (
            cd source
            ls -laR
            terraform init
            terraform plan
            terraform apply -auto-approve
          )
